const IMAGES = [
  {
    id: 0,
    src: require("../assets/images/gallery-images/abstract-001.JPG"),
    description: "Abstract image 001",
    tag: "abstract",
  },
  {
    id: 2,
    src: require("../assets/images/gallery-images/abstract-002.JPG"),
    description: "Abstract image 002",
    tag: "abstract",
  },
  {
    id: 3,
    src: require("../assets/images/gallery-images/abstract-003.JPG"),
    description: "Abstract image 003",
    tag: "abstract",
  },
  {
    id: 4,
    src: require("../assets/images/gallery-images/abstract-004.JPG"),
    description: "Abstract image 004",
    tag: "abstract",
  },
  {
    id: 5,
    src: require("../assets/images/gallery-images/abstract-005.JPG"),
    description: "Abstract image 005",
    tag: "abstract",
  },
  {
    id: 6,
    src: require("../assets/images/gallery-images/abstract-006.JPG"),
    description: "Abstract image 006",
    tag: "abstract",
  },
  {
    id: 7,
    src: require("../assets/images/gallery-images/brand-001.JPG"),
    description: "Brand image 001",
    tag: "brand",
  },
  {
    id: 8,
    src: require("../assets/images/gallery-images/brand-002.JPG"),
    description: "Brand image 002",
    tag: "brand",
  },
  {
    id: 9,
    src: require("../assets/images/gallery-images/brand-003.JPG"),
    description: "Brand image 003",
    tag: "brand",
  },
  {
    id: 10,
    src: require("../assets/images/gallery-images/brand-004.JPG"),
    description: "Brand image 004",
    tag: "brand",
  },
  {
    id: 11,
    src: require("../assets/images/gallery-images/brand-005.JPG"),
    description: "Brand image 005",
    tag: "brand",
  },
  {
    id: 12,
    src: require("../assets/images/gallery-images/brand-006.JPG"),
    description: "Brand image 006",
    tag: "brand",
  },
  {
    id: 13,
    src: require("../assets/images/gallery-images/design-001.JPG"),
    description: "Design image 001",
    tag: "design",
  },
  {
    id: 14,
    src: require("../assets/images/gallery-images/design-002.JPG"),
    description: "Design image 002",
    tag: "design",
  },
  {
    id: 15,
    src: require("../assets/images/gallery-images/design-003.JPG"),
    description: "Design image 003",
    tag: "design",
  },
  {
    id: 16,
    src: require("../assets/images/gallery-images/design-004.JPG"),
    description: "Design image 004",
    tag: "design",
  },
  {
    id: 17,
    src: require("../assets/images/gallery-images/design-005.JPG"),
    description: "Design image 005",
    tag: "design",
  },
  {
    id: 18,
    src: require("../assets/images/gallery-images/design-006.JPG"),
    description: "Design image 006",
    tag: "design",
  },
  {
    id: 19,
    src: require("../assets/images/gallery-images/graphics-001.JPG"),
    description: "Graphics image 001",
    tag: "graphics",
  },
  {
    id: 20,
    src: require("../assets/images/gallery-images/graphics-002.JPG"),
    description: "Graphics image 002",
    tag: "graphics",
  },
  {
    id: 21,
    src: require("../assets/images/gallery-images/graphics-003.JPG"),
    description: "Graphics image 003",
    tag: "graphics",
  },
  {
    id: 22,
    src: require("../assets/images/gallery-images/graphics-004.JPG"),
    description: "Graphics image 004",
    tag: "graphics",
  },
  {
    id: 23,
    src: require("../assets/images/gallery-images/graphics-005.JPG"),
    description: "Graphics image 005",
    tag: "graphics",
  },
  {
    id: 24,
    src: require("../assets/images/gallery-images/graphics-006.JPG"),
    description: "Graphics image 006",
    tag: "graphics",
  },
  {
    id: 25,
    src: require("../assets/images/gallery-images/tech-001.JPG"),
    description: "Tech image 001",
    tag: "tech",
  },
  {
    id: 26,
    src: require("../assets/images/gallery-images/tech-002.JPG"),
    description: "Tech image 002",
    tag: "tech",
  },
  {
    id: 27,
    src: require("../assets/images/gallery-images/tech-003.JPG"),
    description: "Tech image 003",
    tag: "tech",
  },
  {
    id: 28,
    src: require("../assets/images/gallery-images/tech-004.JPG"),
    description: "Tech image 004",
    tag: "tech",
  },
  {
    id: 29,
    src: require("../assets/images/gallery-images/tech-005.JPG"),
    description: "Tech image 005",
    tag: "tech",
  },
  {
    id: 30,
    src: require("../assets/images/gallery-images/tech-006.JPG"),
    description: "Tech image 006",
    tag: "tech",
  },
];

export default IMAGES;
